services:
  mysql:
    container_name: mysqldb
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=ecommerce-cms-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:3306"]
       interval: 10s
       timeout: 5s
       retries: 3
       start_period: 30s 
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net
  web:
    container_name: cmsshoppingcart-web
    build:
      context: .
      dockerfile: ./Dockerfile
    image: thuanvn2002/cmsshoppingcart-web
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-net
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - app-net

volumes:
  mysql-data:

networks:
  app-net:
    driver: bridge
