version: '3.3'

services:
  mysql:
    container_name: mysqldb
    image: mysql
    restart: always
    ports:
      - "3305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=ecommerce-cms-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-cms
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-net
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - app-net

volumes:
  mysql-data:

networks:
  app-net:
    driver: bridge